import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Metadata and og images",
  description: "Generated by create next app",
  openGraph:{
     title: 'The Og Website',
    description: 'Learn more about our company and mission.',
    images: [
      {
        url: '/globe.svg',
        width: 800,
        height: 600,
        alt: 'Og Image Alt',
      },
      {
        url: '/globe.svg',
        width: 1800,
        height: 1600,
        alt: 'Og Image Alt',
      }
    ],
    url: 'http://localhost:3000/about',
  }
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
