import { Geist, Geist_Mono  , Jockey_One} from "next/font/google";
import "./globals.css";

// const jockey_one = Jockey_One({
//      weight:[ "400" ],
//     subsets:["latin"]
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
        {children}
      </body>
    </html>
  );
}
