import React from 'react'

export const metadata = {
  title:{
    default:"Auth | Chai or Code",
    template: "%s | Chai or Code",
    absolute: "",
  },
  description: 'Generated by create next app',
}
const AuthLayout = ({children}) => {
  return (
    <div>
        {children}
    </div>
  )
}

export default AuthLayout